// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: contactInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CAF.Model.CloudHelper.HuaWei {

  /// <summary>Holder for reflection information generated from contactInfo.proto</summary>
  public static partial class ContactInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for contactInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContactInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFjb250YWN0SW5mby5wcm90byJYChFBbGxDb250YWN0c1Jlc3BWbxIgCgZy",
            "ZXN1bHQYASABKAsyEC5Db250YWN0QmFzZVJlc3ASIQoLY29udGFjdExpc3QY",
            "AiADKAsyDC5Db250YWN0QmVhbiI5Cg9Db250YWN0QmFzZVJlc3ASEgoKcmVz",
            "dWx0Q29kZRgBIAEoCRISCgpyZXN1bHREZXNjGAIgASgJItUDCgtDb250YWN0",
            "QmVhbhIRCgljb250YWN0SWQYASABKAkSEwoLZ3JvdXBJZExpc3QYAiADKAkS",
            "EwoEbmFtZRgDIAEoCzIFLk5hbWUSDQoFZk5hbWUYBCABKAkSHQoLYWRkcmVz",
            "c0xpc3QYBSADKAsyCC5BZGRyZXNzEhoKB3RlbExpc3QYBiADKAsyCS5CYXNl",
            "QmVhbhIcCgllbWFpbExpc3QYByADKAsyCS5CYXNlQmVhbhIaCgd1cmxMaXN0",
            "GAggAygLMgkuQmFzZUJlYW4SHwoMb3JnYW5pemVMaXN0GAkgAygLMgkuT3Jn",
            "YW5pemUSGgoHbXNnTGlzdBgKIAMoCzIJLkJhc2VCZWFuEgwKBG5vdGUYCyAB",
            "KAkSEAoIbmlja05hbWUYDCABKAkSFQoNbmlja05hbWVTcGVsbBgNIAEoCRIM",
            "CgRiRGF5GA4gASgJEhEKCWJEYXlMdW5hchgPIAEoCRIQCghwaG90b1VybBgQ",
            "IAEoCRILCgN1aWQYESABKAkSEgoKc2VhcmNoSW5mbxgSIAEoCRIRCgl3aG9s",
            "ZU5hbWUYEyABKAkSFgoOd2hvbGVOYW1lU3BlbGwYFCABKAkSEgoKZXhwaXJl",
            "VGltZRgVIAEoAyLhAQoETmFtZRIRCglmaXJzdE5hbWUYASABKAkSEgoKbWlk",
            "ZGxlTmFtZRgCIAEoCRIQCghsYXN0TmFtZRgDIAEoCRISCgpuYW1lUHJlZml4",
            "GAQgASgJEhIKCm5hbWVTdWZmaXgYBSABKAkSFgoOZmlyc3ROYW1lU3BlbGwY",
            "BiABKAkSFwoPbWlkZGxlTmFtZVNwZWxsGAcgASgJEhUKDWxhc3ROYW1lU3Bl",
            "bGwYCCABKAkSFwoPbmFtZVByZWZpeFNwZWxsGAkgASgJEhcKD25hbWVTdWZm",
            "aXhTcGVsbBgKIAEoCSKcAQoHQWRkcmVzcxISCgpwb3N0YWxDb2RlGAEgASgJ",
            "Eg8KB3Bvc3RCb3gYAiABKAkSDgoGc3RyZWV0GAMgASgJEg8KB2FkZHJlc3MY",
            "BCABKAkSDAoEY2l0eRgFIAEoCRIQCghwcm92aW5jZRgGIAEoCRIPCgdjb3Vu",
            "dHJ5GAcgASgJEgwKBHR5cGUYCCABKAUSDAoEbmFtZRgJIAEoCSI1CghCYXNl",
            "QmVhbhIMCgR0eXBlGAEgASgFEgwKBG5hbWUYAiABKAkSDQoFdmFsdWUYAyAB",
            "KAkiTAoIT3JnYW5pemUSCwoDb3JnGAEgASgJEg0KBXRpdGxlGAIgASgJEhAK",
            "CG9yZ1NwZWxsGAMgASgJEhIKCnRpdGxlU3BlbGwYBCABKAlCH6oCHENBRi5N",
            "b2RlbC5DbG91ZEhlbHBlci5IdWFXZWliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.AllContactsRespVo), global::CAF.Model.CloudHelper.HuaWei.AllContactsRespVo.Parser, new[]{ "Result", "ContactList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp), global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp.Parser, new[]{ "ResultCode", "ResultDesc" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.ContactBean), global::CAF.Model.CloudHelper.HuaWei.ContactBean.Parser, new[]{ "ContactId", "GroupIdList", "Name", "FName", "AddressList", "TelList", "EmailList", "UrlList", "OrganizeList", "MsgList", "Note", "NickName", "NickNameSpell", "BDay", "BDayLunar", "PhotoUrl", "Uid", "SearchInfo", "WholeName", "WholeNameSpell", "ExpireTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.Name), global::CAF.Model.CloudHelper.HuaWei.Name.Parser, new[]{ "FirstName", "MiddleName", "LastName", "NamePrefix", "NameSuffix", "FirstNameSpell", "MiddleNameSpell", "LastNameSpell", "NamePrefixSpell", "NameSuffixSpell" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.Address), global::CAF.Model.CloudHelper.HuaWei.Address.Parser, new[]{ "PostalCode", "PostBox", "Street", "Address_", "City", "Province", "Country", "Type", "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.BaseBean), global::CAF.Model.CloudHelper.HuaWei.BaseBean.Parser, new[]{ "Type", "Name", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.Organize), global::CAF.Model.CloudHelper.HuaWei.Organize.Parser, new[]{ "Org", "Title", "OrgSpell", "TitleSpell" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///联系人返回信息
  /// </summary>
  public sealed partial class AllContactsRespVo : pb::IMessage<AllContactsRespVo> {
    private static readonly pb::MessageParser<AllContactsRespVo> _parser = new pb::MessageParser<AllContactsRespVo>(() => new AllContactsRespVo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AllContactsRespVo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AllContactsRespVo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AllContactsRespVo(AllContactsRespVo other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      contactList_ = other.contactList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AllContactsRespVo Clone() {
      return new AllContactsRespVo(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "contactList" field.</summary>
    public const int ContactListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.ContactBean> _repeated_contactList_codec
        = pb::FieldCodec.ForMessage(18, global::CAF.Model.CloudHelper.HuaWei.ContactBean.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.ContactBean> contactList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.ContactBean>();
    /// <summary>
    ///联系人列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.ContactBean> ContactList {
      get { return contactList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AllContactsRespVo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AllContactsRespVo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if(!contactList_.Equals(other.contactList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      hash ^= contactList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      contactList_.WriteTo(output, _repeated_contactList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      size += contactList_.CalculateSize(_repeated_contactList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AllContactsRespVo other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp();
        }
        Result.MergeFrom(other.Result);
      }
      contactList_.Add(other.contactList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            contactList_.AddEntriesFrom(input, _repeated_contactList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///操作结果
  /// </summary>
  public sealed partial class ContactBaseResp : pb::IMessage<ContactBaseResp> {
    private static readonly pb::MessageParser<ContactBaseResp> _parser = new pb::MessageParser<ContactBaseResp>(() => new ContactBaseResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContactBaseResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactBaseResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactBaseResp(ContactBaseResp other) : this() {
      resultCode_ = other.resultCode_;
      resultDesc_ = other.resultDesc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactBaseResp Clone() {
      return new ContactBaseResp(this);
    }

    /// <summary>Field number for the "resultCode" field.</summary>
    public const int ResultCodeFieldNumber = 1;
    private string resultCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resultDesc" field.</summary>
    public const int ResultDescFieldNumber = 2;
    private string resultDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResultDesc {
      get { return resultDesc_; }
      set {
        resultDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContactBaseResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContactBaseResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultCode != other.ResultCode) return false;
      if (ResultDesc != other.ResultDesc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultCode.Length != 0) hash ^= ResultCode.GetHashCode();
      if (ResultDesc.Length != 0) hash ^= ResultDesc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResultCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResultCode);
      }
      if (ResultDesc.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ResultDesc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResultCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultCode);
      }
      if (ResultDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultDesc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContactBaseResp other) {
      if (other == null) {
        return;
      }
      if (other.ResultCode.Length != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.ResultDesc.Length != 0) {
        ResultDesc = other.ResultDesc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResultCode = input.ReadString();
            break;
          }
          case 18: {
            ResultDesc = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///联系人信息
  /// </summary>
  public sealed partial class ContactBean : pb::IMessage<ContactBean> {
    private static readonly pb::MessageParser<ContactBean> _parser = new pb::MessageParser<ContactBean>(() => new ContactBean());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContactBean> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactBean() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactBean(ContactBean other) : this() {
      contactId_ = other.contactId_;
      groupIdList_ = other.groupIdList_.Clone();
      name_ = other.name_ != null ? other.name_.Clone() : null;
      fName_ = other.fName_;
      addressList_ = other.addressList_.Clone();
      telList_ = other.telList_.Clone();
      emailList_ = other.emailList_.Clone();
      urlList_ = other.urlList_.Clone();
      organizeList_ = other.organizeList_.Clone();
      msgList_ = other.msgList_.Clone();
      note_ = other.note_;
      nickName_ = other.nickName_;
      nickNameSpell_ = other.nickNameSpell_;
      bDay_ = other.bDay_;
      bDayLunar_ = other.bDayLunar_;
      photoUrl_ = other.photoUrl_;
      uid_ = other.uid_;
      searchInfo_ = other.searchInfo_;
      wholeName_ = other.wholeName_;
      wholeNameSpell_ = other.wholeNameSpell_;
      expireTime_ = other.expireTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContactBean Clone() {
      return new ContactBean(this);
    }

    /// <summary>Field number for the "contactId" field.</summary>
    public const int ContactIdFieldNumber = 1;
    private string contactId_ = "";
    /// <summary>
    /// 联系人ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContactId {
      get { return contactId_; }
      set {
        contactId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "groupIdList" field.</summary>
    public const int GroupIdListFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_groupIdList_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> groupIdList_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///所属群组ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GroupIdList {
      get { return groupIdList_; }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private global::CAF.Model.CloudHelper.HuaWei.Name name_;
    /// <summary>
    ///联系人名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CAF.Model.CloudHelper.HuaWei.Name Name {
      get { return name_; }
      set {
        name_ = value;
      }
    }

    /// <summary>Field number for the "fName" field.</summary>
    public const int FNameFieldNumber = 4;
    private string fName_ = "";
    /// <summary>
    ///联系人
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FName {
      get { return fName_; }
      set {
        fName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "addressList" field.</summary>
    public const int AddressListFieldNumber = 5;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.Address> _repeated_addressList_codec
        = pb::FieldCodec.ForMessage(42, global::CAF.Model.CloudHelper.HuaWei.Address.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.Address> addressList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.Address>();
    /// <summary>
    ///地址列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.Address> AddressList {
      get { return addressList_; }
    }

    /// <summary>Field number for the "telList" field.</summary>
    public const int TelListFieldNumber = 6;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.BaseBean> _repeated_telList_codec
        = pb::FieldCodec.ForMessage(50, global::CAF.Model.CloudHelper.HuaWei.BaseBean.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> telList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean>();
    /// <summary>
    ///电话列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> TelList {
      get { return telList_; }
    }

    /// <summary>Field number for the "emailList" field.</summary>
    public const int EmailListFieldNumber = 7;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.BaseBean> _repeated_emailList_codec
        = pb::FieldCodec.ForMessage(58, global::CAF.Model.CloudHelper.HuaWei.BaseBean.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> emailList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean>();
    /// <summary>
    ///邮箱列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> EmailList {
      get { return emailList_; }
    }

    /// <summary>Field number for the "urlList" field.</summary>
    public const int UrlListFieldNumber = 8;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.BaseBean> _repeated_urlList_codec
        = pb::FieldCodec.ForMessage(66, global::CAF.Model.CloudHelper.HuaWei.BaseBean.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> urlList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean>();
    /// <summary>
    ///URL列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> UrlList {
      get { return urlList_; }
    }

    /// <summary>Field number for the "organizeList" field.</summary>
    public const int OrganizeListFieldNumber = 9;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.Organize> _repeated_organizeList_codec
        = pb::FieldCodec.ForMessage(74, global::CAF.Model.CloudHelper.HuaWei.Organize.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.Organize> organizeList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.Organize>();
    /// <summary>
    ///组织结构列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.Organize> OrganizeList {
      get { return organizeList_; }
    }

    /// <summary>Field number for the "msgList" field.</summary>
    public const int MsgListFieldNumber = 10;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.BaseBean> _repeated_msgList_codec
        = pb::FieldCodec.ForMessage(82, global::CAF.Model.CloudHelper.HuaWei.BaseBean.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> msgList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean>();
    /// <summary>
    ///信息列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.BaseBean> MsgList {
      get { return msgList_; }
    }

    /// <summary>Field number for the "note" field.</summary>
    public const int NoteFieldNumber = 11;
    private string note_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Note {
      get { return note_; }
      set {
        note_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 12;
    private string nickName_ = "";
    /// <summary>
    ///联系人昵称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NickName {
      get { return nickName_; }
      set {
        nickName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickNameSpell" field.</summary>
    public const int NickNameSpellFieldNumber = 13;
    private string nickNameSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NickNameSpell {
      get { return nickNameSpell_; }
      set {
        nickNameSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bDay" field.</summary>
    public const int BDayFieldNumber = 14;
    private string bDay_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BDay {
      get { return bDay_; }
      set {
        bDay_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bDayLunar" field.</summary>
    public const int BDayLunarFieldNumber = 15;
    private string bDayLunar_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BDayLunar {
      get { return bDayLunar_; }
      set {
        bDayLunar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "photoUrl" field.</summary>
    public const int PhotoUrlFieldNumber = 16;
    private string photoUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhotoUrl {
      get { return photoUrl_; }
      set {
        photoUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 17;
    private string uid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "searchInfo" field.</summary>
    public const int SearchInfoFieldNumber = 18;
    private string searchInfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SearchInfo {
      get { return searchInfo_; }
      set {
        searchInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "wholeName" field.</summary>
    public const int WholeNameFieldNumber = 19;
    private string wholeName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WholeName {
      get { return wholeName_; }
      set {
        wholeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "wholeNameSpell" field.</summary>
    public const int WholeNameSpellFieldNumber = 20;
    private string wholeNameSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WholeNameSpell {
      get { return wholeNameSpell_; }
      set {
        wholeNameSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expireTime" field.</summary>
    public const int ExpireTimeFieldNumber = 21;
    private long expireTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ExpireTime {
      get { return expireTime_; }
      set {
        expireTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContactBean);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContactBean other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ContactId != other.ContactId) return false;
      if(!groupIdList_.Equals(other.groupIdList_)) return false;
      if (!object.Equals(Name, other.Name)) return false;
      if (FName != other.FName) return false;
      if(!addressList_.Equals(other.addressList_)) return false;
      if(!telList_.Equals(other.telList_)) return false;
      if(!emailList_.Equals(other.emailList_)) return false;
      if(!urlList_.Equals(other.urlList_)) return false;
      if(!organizeList_.Equals(other.organizeList_)) return false;
      if(!msgList_.Equals(other.msgList_)) return false;
      if (Note != other.Note) return false;
      if (NickName != other.NickName) return false;
      if (NickNameSpell != other.NickNameSpell) return false;
      if (BDay != other.BDay) return false;
      if (BDayLunar != other.BDayLunar) return false;
      if (PhotoUrl != other.PhotoUrl) return false;
      if (Uid != other.Uid) return false;
      if (SearchInfo != other.SearchInfo) return false;
      if (WholeName != other.WholeName) return false;
      if (WholeNameSpell != other.WholeNameSpell) return false;
      if (ExpireTime != other.ExpireTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ContactId.Length != 0) hash ^= ContactId.GetHashCode();
      hash ^= groupIdList_.GetHashCode();
      if (name_ != null) hash ^= Name.GetHashCode();
      if (FName.Length != 0) hash ^= FName.GetHashCode();
      hash ^= addressList_.GetHashCode();
      hash ^= telList_.GetHashCode();
      hash ^= emailList_.GetHashCode();
      hash ^= urlList_.GetHashCode();
      hash ^= organizeList_.GetHashCode();
      hash ^= msgList_.GetHashCode();
      if (Note.Length != 0) hash ^= Note.GetHashCode();
      if (NickName.Length != 0) hash ^= NickName.GetHashCode();
      if (NickNameSpell.Length != 0) hash ^= NickNameSpell.GetHashCode();
      if (BDay.Length != 0) hash ^= BDay.GetHashCode();
      if (BDayLunar.Length != 0) hash ^= BDayLunar.GetHashCode();
      if (PhotoUrl.Length != 0) hash ^= PhotoUrl.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (SearchInfo.Length != 0) hash ^= SearchInfo.GetHashCode();
      if (WholeName.Length != 0) hash ^= WholeName.GetHashCode();
      if (WholeNameSpell.Length != 0) hash ^= WholeNameSpell.GetHashCode();
      if (ExpireTime != 0L) hash ^= ExpireTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ContactId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ContactId);
      }
      groupIdList_.WriteTo(output, _repeated_groupIdList_codec);
      if (name_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Name);
      }
      if (FName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FName);
      }
      addressList_.WriteTo(output, _repeated_addressList_codec);
      telList_.WriteTo(output, _repeated_telList_codec);
      emailList_.WriteTo(output, _repeated_emailList_codec);
      urlList_.WriteTo(output, _repeated_urlList_codec);
      organizeList_.WriteTo(output, _repeated_organizeList_codec);
      msgList_.WriteTo(output, _repeated_msgList_codec);
      if (Note.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Note);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(NickName);
      }
      if (NickNameSpell.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(NickNameSpell);
      }
      if (BDay.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(BDay);
      }
      if (BDayLunar.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(BDayLunar);
      }
      if (PhotoUrl.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(PhotoUrl);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(Uid);
      }
      if (SearchInfo.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(SearchInfo);
      }
      if (WholeName.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(WholeName);
      }
      if (WholeNameSpell.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(WholeNameSpell);
      }
      if (ExpireTime != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(ExpireTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ContactId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactId);
      }
      size += groupIdList_.CalculateSize(_repeated_groupIdList_codec);
      if (name_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Name);
      }
      if (FName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FName);
      }
      size += addressList_.CalculateSize(_repeated_addressList_codec);
      size += telList_.CalculateSize(_repeated_telList_codec);
      size += emailList_.CalculateSize(_repeated_emailList_codec);
      size += urlList_.CalculateSize(_repeated_urlList_codec);
      size += organizeList_.CalculateSize(_repeated_organizeList_codec);
      size += msgList_.CalculateSize(_repeated_msgList_codec);
      if (Note.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Note);
      }
      if (NickName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickName);
      }
      if (NickNameSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickNameSpell);
      }
      if (BDay.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BDay);
      }
      if (BDayLunar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BDayLunar);
      }
      if (PhotoUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PhotoUrl);
      }
      if (Uid.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (SearchInfo.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SearchInfo);
      }
      if (WholeName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(WholeName);
      }
      if (WholeNameSpell.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(WholeNameSpell);
      }
      if (ExpireTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ExpireTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContactBean other) {
      if (other == null) {
        return;
      }
      if (other.ContactId.Length != 0) {
        ContactId = other.ContactId;
      }
      groupIdList_.Add(other.groupIdList_);
      if (other.name_ != null) {
        if (name_ == null) {
          Name = new global::CAF.Model.CloudHelper.HuaWei.Name();
        }
        Name.MergeFrom(other.Name);
      }
      if (other.FName.Length != 0) {
        FName = other.FName;
      }
      addressList_.Add(other.addressList_);
      telList_.Add(other.telList_);
      emailList_.Add(other.emailList_);
      urlList_.Add(other.urlList_);
      organizeList_.Add(other.organizeList_);
      msgList_.Add(other.msgList_);
      if (other.Note.Length != 0) {
        Note = other.Note;
      }
      if (other.NickName.Length != 0) {
        NickName = other.NickName;
      }
      if (other.NickNameSpell.Length != 0) {
        NickNameSpell = other.NickNameSpell;
      }
      if (other.BDay.Length != 0) {
        BDay = other.BDay;
      }
      if (other.BDayLunar.Length != 0) {
        BDayLunar = other.BDayLunar;
      }
      if (other.PhotoUrl.Length != 0) {
        PhotoUrl = other.PhotoUrl;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.SearchInfo.Length != 0) {
        SearchInfo = other.SearchInfo;
      }
      if (other.WholeName.Length != 0) {
        WholeName = other.WholeName;
      }
      if (other.WholeNameSpell.Length != 0) {
        WholeNameSpell = other.WholeNameSpell;
      }
      if (other.ExpireTime != 0L) {
        ExpireTime = other.ExpireTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ContactId = input.ReadString();
            break;
          }
          case 18: {
            groupIdList_.AddEntriesFrom(input, _repeated_groupIdList_codec);
            break;
          }
          case 26: {
            if (name_ == null) {
              Name = new global::CAF.Model.CloudHelper.HuaWei.Name();
            }
            input.ReadMessage(Name);
            break;
          }
          case 34: {
            FName = input.ReadString();
            break;
          }
          case 42: {
            addressList_.AddEntriesFrom(input, _repeated_addressList_codec);
            break;
          }
          case 50: {
            telList_.AddEntriesFrom(input, _repeated_telList_codec);
            break;
          }
          case 58: {
            emailList_.AddEntriesFrom(input, _repeated_emailList_codec);
            break;
          }
          case 66: {
            urlList_.AddEntriesFrom(input, _repeated_urlList_codec);
            break;
          }
          case 74: {
            organizeList_.AddEntriesFrom(input, _repeated_organizeList_codec);
            break;
          }
          case 82: {
            msgList_.AddEntriesFrom(input, _repeated_msgList_codec);
            break;
          }
          case 90: {
            Note = input.ReadString();
            break;
          }
          case 98: {
            NickName = input.ReadString();
            break;
          }
          case 106: {
            NickNameSpell = input.ReadString();
            break;
          }
          case 114: {
            BDay = input.ReadString();
            break;
          }
          case 122: {
            BDayLunar = input.ReadString();
            break;
          }
          case 130: {
            PhotoUrl = input.ReadString();
            break;
          }
          case 138: {
            Uid = input.ReadString();
            break;
          }
          case 146: {
            SearchInfo = input.ReadString();
            break;
          }
          case 154: {
            WholeName = input.ReadString();
            break;
          }
          case 162: {
            WholeNameSpell = input.ReadString();
            break;
          }
          case 168: {
            ExpireTime = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///联系人名称详情
  /// </summary>
  public sealed partial class Name : pb::IMessage<Name> {
    private static readonly pb::MessageParser<Name> _parser = new pb::MessageParser<Name>(() => new Name());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Name> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Name() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Name(Name other) : this() {
      firstName_ = other.firstName_;
      middleName_ = other.middleName_;
      lastName_ = other.lastName_;
      namePrefix_ = other.namePrefix_;
      nameSuffix_ = other.nameSuffix_;
      firstNameSpell_ = other.firstNameSpell_;
      middleNameSpell_ = other.middleNameSpell_;
      lastNameSpell_ = other.lastNameSpell_;
      namePrefixSpell_ = other.namePrefixSpell_;
      nameSuffixSpell_ = other.nameSuffixSpell_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Name Clone() {
      return new Name(this);
    }

    /// <summary>Field number for the "firstName" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "middleName" field.</summary>
    public const int MiddleNameFieldNumber = 2;
    private string middleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MiddleName {
      get { return middleName_; }
      set {
        middleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastName" field.</summary>
    public const int LastNameFieldNumber = 3;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "namePrefix" field.</summary>
    public const int NamePrefixFieldNumber = 4;
    private string namePrefix_ = "";
    /// <summary>
    ///名称前缀
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NamePrefix {
      get { return namePrefix_; }
      set {
        namePrefix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nameSuffix" field.</summary>
    public const int NameSuffixFieldNumber = 5;
    private string nameSuffix_ = "";
    /// <summary>
    ///名称后缀
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameSuffix {
      get { return nameSuffix_; }
      set {
        nameSuffix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "firstNameSpell" field.</summary>
    public const int FirstNameSpellFieldNumber = 6;
    private string firstNameSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FirstNameSpell {
      get { return firstNameSpell_; }
      set {
        firstNameSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "middleNameSpell" field.</summary>
    public const int MiddleNameSpellFieldNumber = 7;
    private string middleNameSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MiddleNameSpell {
      get { return middleNameSpell_; }
      set {
        middleNameSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastNameSpell" field.</summary>
    public const int LastNameSpellFieldNumber = 8;
    private string lastNameSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastNameSpell {
      get { return lastNameSpell_; }
      set {
        lastNameSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "namePrefixSpell" field.</summary>
    public const int NamePrefixSpellFieldNumber = 9;
    private string namePrefixSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NamePrefixSpell {
      get { return namePrefixSpell_; }
      set {
        namePrefixSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nameSuffixSpell" field.</summary>
    public const int NameSuffixSpellFieldNumber = 10;
    private string nameSuffixSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameSuffixSpell {
      get { return nameSuffixSpell_; }
      set {
        nameSuffixSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Name);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Name other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (MiddleName != other.MiddleName) return false;
      if (LastName != other.LastName) return false;
      if (NamePrefix != other.NamePrefix) return false;
      if (NameSuffix != other.NameSuffix) return false;
      if (FirstNameSpell != other.FirstNameSpell) return false;
      if (MiddleNameSpell != other.MiddleNameSpell) return false;
      if (LastNameSpell != other.LastNameSpell) return false;
      if (NamePrefixSpell != other.NamePrefixSpell) return false;
      if (NameSuffixSpell != other.NameSuffixSpell) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (MiddleName.Length != 0) hash ^= MiddleName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (NamePrefix.Length != 0) hash ^= NamePrefix.GetHashCode();
      if (NameSuffix.Length != 0) hash ^= NameSuffix.GetHashCode();
      if (FirstNameSpell.Length != 0) hash ^= FirstNameSpell.GetHashCode();
      if (MiddleNameSpell.Length != 0) hash ^= MiddleNameSpell.GetHashCode();
      if (LastNameSpell.Length != 0) hash ^= LastNameSpell.GetHashCode();
      if (NamePrefixSpell.Length != 0) hash ^= NamePrefixSpell.GetHashCode();
      if (NameSuffixSpell.Length != 0) hash ^= NameSuffixSpell.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (NamePrefix.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NamePrefix);
      }
      if (NameSuffix.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NameSuffix);
      }
      if (FirstNameSpell.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FirstNameSpell);
      }
      if (MiddleNameSpell.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(MiddleNameSpell);
      }
      if (LastNameSpell.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(LastNameSpell);
      }
      if (NamePrefixSpell.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(NamePrefixSpell);
      }
      if (NameSuffixSpell.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(NameSuffixSpell);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (MiddleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MiddleName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (NamePrefix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NamePrefix);
      }
      if (NameSuffix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameSuffix);
      }
      if (FirstNameSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstNameSpell);
      }
      if (MiddleNameSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MiddleNameSpell);
      }
      if (LastNameSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastNameSpell);
      }
      if (NamePrefixSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NamePrefixSpell);
      }
      if (NameSuffixSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameSuffixSpell);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Name other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.MiddleName.Length != 0) {
        MiddleName = other.MiddleName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.NamePrefix.Length != 0) {
        NamePrefix = other.NamePrefix;
      }
      if (other.NameSuffix.Length != 0) {
        NameSuffix = other.NameSuffix;
      }
      if (other.FirstNameSpell.Length != 0) {
        FirstNameSpell = other.FirstNameSpell;
      }
      if (other.MiddleNameSpell.Length != 0) {
        MiddleNameSpell = other.MiddleNameSpell;
      }
      if (other.LastNameSpell.Length != 0) {
        LastNameSpell = other.LastNameSpell;
      }
      if (other.NamePrefixSpell.Length != 0) {
        NamePrefixSpell = other.NamePrefixSpell;
      }
      if (other.NameSuffixSpell.Length != 0) {
        NameSuffixSpell = other.NameSuffixSpell;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            MiddleName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 34: {
            NamePrefix = input.ReadString();
            break;
          }
          case 42: {
            NameSuffix = input.ReadString();
            break;
          }
          case 50: {
            FirstNameSpell = input.ReadString();
            break;
          }
          case 58: {
            MiddleNameSpell = input.ReadString();
            break;
          }
          case 66: {
            LastNameSpell = input.ReadString();
            break;
          }
          case 74: {
            NamePrefixSpell = input.ReadString();
            break;
          }
          case 82: {
            NameSuffixSpell = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///联系人地址详情
  /// </summary>
  public sealed partial class Address : pb::IMessage<Address> {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address(Address other) : this() {
      postalCode_ = other.postalCode_;
      postBox_ = other.postBox_;
      street_ = other.street_;
      address_ = other.address_;
      city_ = other.city_;
      province_ = other.province_;
      country_ = other.country_;
      type_ = other.type_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "postalCode" field.</summary>
    public const int PostalCodeFieldNumber = 1;
    private string postalCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PostalCode {
      get { return postalCode_; }
      set {
        postalCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "postBox" field.</summary>
    public const int PostBoxFieldNumber = 2;
    private string postBox_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PostBox {
      get { return postBox_; }
      set {
        postBox_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "street" field.</summary>
    public const int StreetFieldNumber = 3;
    private string street_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Street {
      get { return street_; }
      set {
        street_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int Address_FieldNumber = 4;
    private string address_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Address_ {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 5;
    private string city_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "province" field.</summary>
    public const int ProvinceFieldNumber = 6;
    private string province_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Province {
      get { return province_; }
      set {
        province_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 7;
    private string country_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Country {
      get { return country_; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 8;
    private int type_;
    /// <summary>
    ///地址类型 0:自定义 1：家庭 2：工作 3：其他
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 9;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PostalCode != other.PostalCode) return false;
      if (PostBox != other.PostBox) return false;
      if (Street != other.Street) return false;
      if (Address_ != other.Address_) return false;
      if (City != other.City) return false;
      if (Province != other.Province) return false;
      if (Country != other.Country) return false;
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PostalCode.Length != 0) hash ^= PostalCode.GetHashCode();
      if (PostBox.Length != 0) hash ^= PostBox.GetHashCode();
      if (Street.Length != 0) hash ^= Street.GetHashCode();
      if (Address_.Length != 0) hash ^= Address_.GetHashCode();
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (Province.Length != 0) hash ^= Province.GetHashCode();
      if (Country.Length != 0) hash ^= Country.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PostalCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PostalCode);
      }
      if (PostBox.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PostBox);
      }
      if (Street.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Street);
      }
      if (Address_.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Address_);
      }
      if (City.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(City);
      }
      if (Province.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Province);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Country);
      }
      if (Type != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PostalCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PostalCode);
      }
      if (PostBox.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PostBox);
      }
      if (Street.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Street);
      }
      if (Address_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address_);
      }
      if (City.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (Province.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Province);
      }
      if (Country.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      if (other.PostalCode.Length != 0) {
        PostalCode = other.PostalCode;
      }
      if (other.PostBox.Length != 0) {
        PostBox = other.PostBox;
      }
      if (other.Street.Length != 0) {
        Street = other.Street;
      }
      if (other.Address_.Length != 0) {
        Address_ = other.Address_;
      }
      if (other.City.Length != 0) {
        City = other.City;
      }
      if (other.Province.Length != 0) {
        Province = other.Province;
      }
      if (other.Country.Length != 0) {
        Country = other.Country;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PostalCode = input.ReadString();
            break;
          }
          case 18: {
            PostBox = input.ReadString();
            break;
          }
          case 26: {
            Street = input.ReadString();
            break;
          }
          case 34: {
            Address_ = input.ReadString();
            break;
          }
          case 42: {
            City = input.ReadString();
            break;
          }
          case 50: {
            Province = input.ReadString();
            break;
          }
          case 58: {
            Country = input.ReadString();
            break;
          }
          case 64: {
            Type = input.ReadInt32();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///基础信息类
  /// </summary>
  public sealed partial class BaseBean : pb::IMessage<BaseBean> {
    private static readonly pb::MessageParser<BaseBean> _parser = new pb::MessageParser<BaseBean>(() => new BaseBean());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BaseBean> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BaseBean() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BaseBean(BaseBean other) : this() {
      type_ = other.type_;
      name_ = other.name_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BaseBean Clone() {
      return new BaseBean(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BaseBean);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BaseBean other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BaseBean other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///组织机构信息
  /// </summary>
  public sealed partial class Organize : pb::IMessage<Organize> {
    private static readonly pb::MessageParser<Organize> _parser = new pb::MessageParser<Organize>(() => new Organize());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Organize> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Organize() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Organize(Organize other) : this() {
      org_ = other.org_;
      title_ = other.title_;
      orgSpell_ = other.orgSpell_;
      titleSpell_ = other.titleSpell_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Organize Clone() {
      return new Organize(this);
    }

    /// <summary>Field number for the "org" field.</summary>
    public const int OrgFieldNumber = 1;
    private string org_ = "";
    /// <summary>
    ///组织名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Org {
      get { return org_; }
      set {
        org_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    /// <summary>
    ///职务
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "orgSpell" field.</summary>
    public const int OrgSpellFieldNumber = 3;
    private string orgSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrgSpell {
      get { return orgSpell_; }
      set {
        orgSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "titleSpell" field.</summary>
    public const int TitleSpellFieldNumber = 4;
    private string titleSpell_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TitleSpell {
      get { return titleSpell_; }
      set {
        titleSpell_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Organize);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Organize other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Org != other.Org) return false;
      if (Title != other.Title) return false;
      if (OrgSpell != other.OrgSpell) return false;
      if (TitleSpell != other.TitleSpell) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Org.Length != 0) hash ^= Org.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (OrgSpell.Length != 0) hash ^= OrgSpell.GetHashCode();
      if (TitleSpell.Length != 0) hash ^= TitleSpell.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Org.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Org);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (OrgSpell.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrgSpell);
      }
      if (TitleSpell.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TitleSpell);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Org.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Org);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (OrgSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrgSpell);
      }
      if (TitleSpell.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitleSpell);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Organize other) {
      if (other == null) {
        return;
      }
      if (other.Org.Length != 0) {
        Org = other.Org;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.OrgSpell.Length != 0) {
        OrgSpell = other.OrgSpell;
      }
      if (other.TitleSpell.Length != 0) {
        TitleSpell = other.TitleSpell;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Org = input.ReadString();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            OrgSpell = input.ReadString();
            break;
          }
          case 34: {
            TitleSpell = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
