// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: groupInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CAF.Model.CloudHelper.HuaWei {

  /// <summary>Holder for reflection information generated from groupInfo.proto</summary>
  public static partial class GroupInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for groupInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GroupInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9ncm91cEluZm8ucHJvdG8aEWNvbnRhY3RJbmZvLnByb3RvIlUKD0FsbEdy",
            "b3Vwc1Jlc3BWbxIgCgZyZXN1bHQYASABKAsyEC5Db250YWN0QmFzZVJlc3AS",
            "IAoJZ3JvdXBMaXN0GAIgAygLMg0uR3JvdXBJbmZvUmVxInYKDEdyb3VwSW5m",
            "b1JlcRIVCg1jb250YWN0SWRMaXN0GAEgAygJEg8KB2dyb3VwSWQYAiABKAkS",
            "EQoJZ3JvdXBOYW1lGAMgASgJEhIKCnVwZGF0ZVRpbWUYBCABKAQSFwoPY29u",
            "dGFjdFV1SWRMaXN0GAUgAygJQh+qAhxDQUYuTW9kZWwuQ2xvdWRIZWxwZXIu",
            "SHVhV2VpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CAF.Model.CloudHelper.HuaWei.ContactInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.AllGroupsRespVo), global::CAF.Model.CloudHelper.HuaWei.AllGroupsRespVo.Parser, new[]{ "Result", "GroupList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq), global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq.Parser, new[]{ "ContactIdList", "GroupId", "GroupName", "UpdateTime", "ContactUuIdList" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///联系人返回信息
  /// </summary>
  public sealed partial class AllGroupsRespVo : pb::IMessage<AllGroupsRespVo> {
    private static readonly pb::MessageParser<AllGroupsRespVo> _parser = new pb::MessageParser<AllGroupsRespVo>(() => new AllGroupsRespVo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AllGroupsRespVo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.GroupInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AllGroupsRespVo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AllGroupsRespVo(AllGroupsRespVo other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      groupList_ = other.groupList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AllGroupsRespVo Clone() {
      return new AllGroupsRespVo(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "groupList" field.</summary>
    public const int GroupListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq> _repeated_groupList_codec
        = pb::FieldCodec.ForMessage(18, global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq.Parser);
    private readonly pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq> groupList_ = new pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq>();
    /// <summary>
    ///群组列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CAF.Model.CloudHelper.HuaWei.GroupInfoReq> GroupList {
      get { return groupList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AllGroupsRespVo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AllGroupsRespVo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if(!groupList_.Equals(other.groupList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      hash ^= groupList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      groupList_.WriteTo(output, _repeated_groupList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      size += groupList_.CalculateSize(_repeated_groupList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AllGroupsRespVo other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp();
        }
        Result.MergeFrom(other.Result);
      }
      groupList_.Add(other.groupList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::CAF.Model.CloudHelper.HuaWei.ContactBaseResp();
            }
            input.ReadMessage(Result);
            break;
          }
          case 18: {
            groupList_.AddEntriesFrom(input, _repeated_groupList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///联系人信息
  /// </summary>
  public sealed partial class GroupInfoReq : pb::IMessage<GroupInfoReq> {
    private static readonly pb::MessageParser<GroupInfoReq> _parser = new pb::MessageParser<GroupInfoReq>(() => new GroupInfoReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GroupInfoReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CAF.Model.CloudHelper.HuaWei.GroupInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupInfoReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupInfoReq(GroupInfoReq other) : this() {
      contactIdList_ = other.contactIdList_.Clone();
      groupId_ = other.groupId_;
      groupName_ = other.groupName_;
      updateTime_ = other.updateTime_;
      contactUuIdList_ = other.contactUuIdList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GroupInfoReq Clone() {
      return new GroupInfoReq(this);
    }

    /// <summary>Field number for the "contactIdList" field.</summary>
    public const int ContactIdListFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_contactIdList_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> contactIdList_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///联系人ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ContactIdList {
      get { return contactIdList_; }
    }

    /// <summary>Field number for the "groupId" field.</summary>
    public const int GroupIdFieldNumber = 2;
    private string groupId_ = "";
    /// <summary>
    ///群组ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GroupId {
      get { return groupId_; }
      set {
        groupId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "groupName" field.</summary>
    public const int GroupNameFieldNumber = 3;
    private string groupName_ = "";
    /// <summary>
    ///群组名字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GroupName {
      get { return groupName_; }
      set {
        groupName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "updateTime" field.</summary>
    public const int UpdateTimeFieldNumber = 4;
    private ulong updateTime_;
    /// <summary>
    ///更新时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UpdateTime {
      get { return updateTime_; }
      set {
        updateTime_ = value;
      }
    }

    /// <summary>Field number for the "contactUuIdList" field.</summary>
    public const int ContactUuIdListFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_contactUuIdList_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> contactUuIdList_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///联系人UUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ContactUuIdList {
      get { return contactUuIdList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GroupInfoReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GroupInfoReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!contactIdList_.Equals(other.contactIdList_)) return false;
      if (GroupId != other.GroupId) return false;
      if (GroupName != other.GroupName) return false;
      if (UpdateTime != other.UpdateTime) return false;
      if(!contactUuIdList_.Equals(other.contactUuIdList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= contactIdList_.GetHashCode();
      if (GroupId.Length != 0) hash ^= GroupId.GetHashCode();
      if (GroupName.Length != 0) hash ^= GroupName.GetHashCode();
      if (UpdateTime != 0UL) hash ^= UpdateTime.GetHashCode();
      hash ^= contactUuIdList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      contactIdList_.WriteTo(output, _repeated_contactIdList_codec);
      if (GroupId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GroupId);
      }
      if (GroupName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GroupName);
      }
      if (UpdateTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(UpdateTime);
      }
      contactUuIdList_.WriteTo(output, _repeated_contactUuIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += contactIdList_.CalculateSize(_repeated_contactIdList_codec);
      if (GroupId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupId);
      }
      if (GroupName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupName);
      }
      if (UpdateTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UpdateTime);
      }
      size += contactUuIdList_.CalculateSize(_repeated_contactUuIdList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GroupInfoReq other) {
      if (other == null) {
        return;
      }
      contactIdList_.Add(other.contactIdList_);
      if (other.GroupId.Length != 0) {
        GroupId = other.GroupId;
      }
      if (other.GroupName.Length != 0) {
        GroupName = other.GroupName;
      }
      if (other.UpdateTime != 0UL) {
        UpdateTime = other.UpdateTime;
      }
      contactUuIdList_.Add(other.contactUuIdList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            contactIdList_.AddEntriesFrom(input, _repeated_contactIdList_codec);
            break;
          }
          case 18: {
            GroupId = input.ReadString();
            break;
          }
          case 26: {
            GroupName = input.ReadString();
            break;
          }
          case 32: {
            UpdateTime = input.ReadUInt64();
            break;
          }
          case 42: {
            contactUuIdList_.AddEntriesFrom(input, _repeated_contactUuIdList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
